config/routes.rb
Rails.application.routes.draw do

  resources :categories
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :items do
    member do
      post :add_to_cart
    end

    resources :comments, only: [:create]
    # 做一條留言的連結
  end
  # resources :comments 沒必要全做，做上面create就好。
  # resources :items 自動做八條路徑
  # post "/abc/:id", to: "cart#add", as: :cc

    resource :cart, only: [:show, :destroy]

  get "/item", to: "items#index"
  post "/item", to: "items#creat"



  # welcome
  get "/index", to: "welcome#index" #welcome_index_path
  root "items#index" #root_path
  get "/login", to:"welcome#login"
  post "/login", to:"welcome#sign_in"
  get "/sign_up", to:"welcome#sign_up"
  post "/sign_up", to:"welcome#registration"
  delete "/logout", to:"welcome#logout"
  
  # cart沒寫完
  post "/abc/:id", to:"cart#add", as: :cc 
   # as: :cc 網址會加個path

   resource :cart, only:  [:create]
   # 單數，因為只有一台購物車

   # POST ""

  # item

  # apis
  namespace :api do
    namespace :v1 do
      resources :items, only: [] do
        member do 
         post :favorite
        end
      end
    end
  end

  
			
end

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
	<div class="alert alert-success" role="alert">
	   <%= flash[:notice] %>
	</div>
<% end %>

<% if flash[:alert] %>
	<div class="alert alert-danger" role="alert">
	   <%= flash[:alert] %>
	</div>
<% end %>

app/views/shared/_footer.html.erb
2020 &copy KK

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
 <a class="navbar-brand" href="#">訂便當</a>
 <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
 <span class="navbar-toggler-icon"></span>
 </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">


  <ul class="navbar-nav mr-auto"> 
  <li class="nav-item">  
    <%= link_to "餐點列表", items_path, class: 'nav-link' %>
  </li> 


    
    <% if current_user %>    
    <li class="nav-item">   
      <%= link_to '我要開團', "#", class: 'nav-link' %>
    </li>
    <% else %>
    <li class="nav-item">  
      <a href="/sign_up" class="nav-link">註冊</a>
    </li>
    <li class="nav-item"> 
      <a href="/login" class="nav-link">登入</a>
    </li>
    <% end %>
    </ul>


    <% if current_user %>
     
    <ul class="navbar-nav">
    <li>
      <%= link_to cart_path, class: 'nav-link' do %>
       購物車 <i class="fas fa-shopping-cart"></i>
       <%= current_cart.items.count %>
     <% end %>
    </li>
     <li>
      <a href="#" class="nav-link">日安,<%= current_user.email %></a>
    </li>
    <li class="nav-item">
    <%= link_to "登出", logout_path, method: 'delete', class: 'nav-link' %>
    </li>
    
    </ul>
    <% end %>
  </div>
</nav>

          
