config/routes.rb
Rails.application.routes.draw do

  resources :categories
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :items do
    member do
      post :add_to_cart
    end

    resources :comments, only: [:create]
    # 做一條留言的連結
  end
  # resources :comments 沒必要全做，做上面create就好。
  # resources :items 自動做八條路徑
  # post "/abc/:id", to: "cart#add", as: :cc

    resource :cart, only: [:show, :destroy]

  get "/item", to: "items#index"
  post "/item", to: "items#creat"



  # welcome
  get "/index", to: "welcome#index" #welcome_index_path
  root "items#index" #root_path
  get "/login", to:"welcome#login"
  post "/login", to:"welcome#sign_in"
  get "/sign_up", to:"welcome#sign_up"
  post "/sign_up", to:"welcome#registration"
  delete "/logout", to:"welcome#logout"
  
  # cart沒寫完
  post "/abc/:id", to:"cart#add", as: :cc 
   # as: :cc 網址會加個path

   resource :cart, only:  [:create]
   # 單數，因為只有一台購物車

   # POST ""

  # item

  # apis
  namespace :api do
    namespace :v1 do
      resources :items, only: [] do
        member do 
         post :favorite
        end
      end
    end
  end

  
			
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	  skip_before_action :check_login

		def index
			# render html: "hi"	
	  end

	
	def login
		@user = User.new
	end

  def sign_up
  	@user = User.new
  end
  

  def sign_in
    user = User.find_by(email: user_params[:email],
	                      password: user_params[:password])
	  if user
	  	session[:kkk1230] = user.id 
	  	# 本來是mail改成id
	  	# 日安, <%= id[:kkk1230] %>
	  	redirect_to "/"
	  else
	  	redirect_to "/login"
	  end
  end


	def registration
		# user = params[:user]
		# p user[:password]
		# p user[:password_confirm]
		# if user_params[:password] == user_params[:password_confirm]
		# Strong parameters
		# clean_user = params.require(:user).permit(:email, :password_confirm)		
		@user = User.new(user_params)

		if @user.save
			session[:kkk1230] = @user.email

		  redirect_to "/login"
	  else
	  	render :sign_up
		  # J個失敗不會轉址，留在原地。
			# redirect_to "/sign_up 這個原本填的資料會不見，不好"
		end

	  # else
	  # 	redirect_to "/sign_up"
    #   end
  end


  def logout
  	session[:kkk1230] = nil
  	redirect_to "/"
  end




  private

  def user_params
  		params.require(:user).permit(:email, 
  																 :password, 
  																 :password_confirmation)
  end





end
  

app/views/welcome/index.html.erb
		<h1 style="color: #59d; font-family: 微軟正黑體;">HI!這是首頁!!</h1>

			<!-- <form action="/login" method="post" style="padding-top: 20px;">
			Email : <input type="text" name="signin" style="margin:10px;"> <br>
			Password : <input type="text" name="passw" style="margin: 10px;"><br>

			<input type="submit" name="確認" value="送出" style="margin: 10px 0;">
      </form> -->
      
		


  	<div>
  		<!-- 你好
  		<img src="https://picsum.photos/g/200/300"> -->
  	</div>
    

app/views/welcome/login.html.erb
<h1 style="color: #6da; font-family: 微軟正黑體;">使用者登入</h1>

<%=	form_for(@user, url: login_path, method:'post') do |f| %>

          <div>
					<%= f.label :email %>
					<%= f.text_field :email %>
					</div><br>
					<div>
					<%= f.label :password, "密碼" %>
					<%= f.password_field :password %>
				  
					</div><br>
					
					<%= f.submit "登入" %>
					
<% end %>


app/views/welcome/sign_up.html.erb


<h1 style="color: #a24; font-family: 微軟正黑體;">使用者註冊</h1>
			
			<%=	form_for(@user, url: '/sign_up', method:'post') do |f| %> <!-- 自動加token -->

			<% if @user.errors.any? %>
					<ul>
							<%  @user.errors.full_messages.each do |message| %>
							<li><%= message %></li>
						<% end %>
					</ul>
			<% end %>
			
					<div>
					<%= f.label :email %>
					<%= f.text_field :email %>
					<!-- <input type="text" name="signup" style="margin:10px;"> -->
					</div><br>
					<div>
					<%= f.label :password, "密碼" %>
					<%= f.password_field :password %>
					<!-- <input type="password" name="password" style="margin: 10px;">  --><br>
					</div><br>
					<div>
					<%= f.label :password_confirmation, "密碼確認" %>
					<%= f.password_field :password_confirmation %>
				<!-- 	<input type="password_confirm" name="passwordconfirm" style="margin: 10px;"> --><br>
					</div><br>
					<%= f.submit "註冊" %>
					<!-- <input type="submit" name="確認" value="註冊" style="margin: 10px 0;"> -->
    <% end %>

			<!-- <form action="/sign_up" method="post" style="padding-top: 20px;">
			
      </form> -->
     
		