config/routes.rb
Rails.application.routes.draw do

  resources :categories
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :items do
    member do
      post :add_to_cart
    end

    resources :comments, only: [:create]
    # 做一條留言的連結
  end
  # resources :comments 沒必要全做，做上面create就好。
  # resources :items 自動做八條路徑
  # post "/abc/:id", to: "cart#add", as: :cc

    resource :cart, only: [:show, :destroy]

  get "/item", to: "items#index"
  post "/item", to: "items#creat"



  # welcome
  get "/index", to: "welcome#index" #welcome_index_path
  root "items#index" #root_path
  get "/login", to:"welcome#login"
  post "/login", to:"welcome#sign_in"
  get "/sign_up", to:"welcome#sign_up"
  post "/sign_up", to:"welcome#registration"
  delete "/logout", to:"welcome#logout"
  
  # cart沒寫完
  post "/abc/:id", to:"cart#add", as: :cc 
   # as: :cc 網址會加個path

   resource :cart, only:  [:create]
   # 單數，因為只有一台購物車

   # POST ""

  # item

  # apis
  namespace :api do
    namespace :v1 do
      resources :items, only: [] do
        member do 
         post :favorite
        end
      end
    end
  end

  
			
end

app/models/item.rb
class Item < ApplicationRecord
	validates :name, presence: true
	validates :price, presence: true, 
	                  numericality: { greater_than: 0 }

  belongs_to :category
  has_one_attached :cover
  has_many :comments
  has_many :favorite_items
  has_many :users, through: :favorite_items

  # scope :available, -> { where(deleted_at: nil)}

  default_scope {where(deleted_at: nil)}
  # 讓刪除的資料真的找不到
  # 嘗試把東西刪掉，再救回來。4/13 2:35 開始
  # Item.unscope(:where).where.not(delete_at: nil)   unscope 解除預設篩選的功能(終端機)
  # 按刪除後會給時間戳記，執行以上摳會將集間戳記還原成nil，重新整理後東西會回來。
  # Item.all 看共刪除了啥 

  def destroy
  	update(deleted_at: Time.now) 	
  end

  
  def favorited_by(u)
  	u.items.include?(self)

  end


end

# add_column :items, :deleted_at, :datetime
# add_index :items, :deleted_at

app/controllers/api/v1/items_controller.rb
class Api::V1::ItemsController < ApplicationController
	#  :verity_authenticity_token
	# skip_before_action :check_loign

	def favorite
		item = Item.find(params[:id])
		if item.favorited_by(current_user)
			 # 移除最愛
			 current_user.items.delete(item)
			 render json: {status: '-'}
		  else
		   current_user.items << item
		  	# +最愛
		   render json: {status: 'favorited'}
		  end 
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

		before_action :find_item, only: [:show, :edit, :update, :destroy, :add_to_cart ]
		                        # except: [:index, :new, :create] 另一個寫法
		# :show, :edit, :update, :destroy 先找好東西
		

		def index
			@items = Item.all
			# 這邊名字沒有一定
			# 只撈沒有暫時刪掉的
			# @items = Item.available 類別方法
			# scope :available, -> { where(deleted_at: nil)} 包去models，不要放controller。
			# scope :cheap, -> { where("price <= 80")} 只是示範
		end
		
    def show
			@comment = Comment.new
			@comments = @item.comments.includes(:user) 
			# 上面改善n+1 query的問題，用IN
			# @comments = @item.comments.order(id: :desc) <!-- .order(id: :desc) 讓他正向排列-->
			# find_item
			# 上面有寫before_action 
			# begin
				# @item = Item.find(params[:id])
			# rescue
			# redirect_to items_path, notice: "沒有品項!"
			# end
		end

		def new
			@item = Item.new
		end


		def create
			@item = Item.new(item_params)

			if @item.save
				# flash[:notice] = "成功新增餐點!"

				redirect_to items_path, notice: "成功新增餐點!"
		  else
		  	render :new
		  end
		end



		def destroy
			# find_item
			# item = Item.find(params[:id])
			@item.destroy
			# @item.update(deleted_at: Time.now)
			redirect_to items_path, notice: "成功刪除餐點!"
		end



	


		def edit
			  # find_item
				# @item = Item.find(params[:id])
				# @item = Item.new 不顯示暫存資料
		end


		def update
			  # find_item
				# @item = Item.find(params[:id])

				if @item.update(item_params)
					 redirect_to items_path, notice: "成功更新餐點!"
				else
					 render :edit
				end
		end


    def add_to_cart
    	# cart = Cart.from_hash(session[:carty])
    	current_cart.add_item(@item.id)
    	session[:carty] = current_cart.to_hash

		  redirect_to root_path, notice: "已加入購物車!"
   	end
   	#之前寫的測試





	private

	def find_item
		  @item = Item.find(params[:id])
			# @item = Item.find_by!(id: params[:id], deleted_at: nil )
	end
	# 一直重複所以做一個一起用


  def item_params
  		params.require(:item).permit(:name, 
  																 :price,
  																 :category_id, 
  																 :description,
  																 :cover,
  																 :spec)
  end



end

app/helpers/api/v1/items_helper.rb
module Api::V1::ItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<!--  new edit 共用 -->

 <%= form_for(item) do |f| %>

       <% if item.errors.any? %>
 					<ul>
 							<% item.errors.full_messages.each do |message| %>
 							<li><%= message %></li>
 						<% end %>
 					</ul>
 			<% end %>

 			<div>
 				<%= f.label :cover %>
 				<%= f.file_field :cover %>
 			</div>

			<div class="">
		    <%= f.label :category %>
		    <%= f.collection_select :category_id, Category.all, :id, :name, prompt: true  %>
	    </div>

 		  <div>
 		    <%= f.label :name %>
 		    <%= f.text_field :name %>
 		  </div>
 		  <div>
 		    <%= f.label :description %>
 		    <%= f.text_area :description %>
 		  </div>
 		  <div>
 		    <%= f.label :price %>
 		    <%= f.number_field :price %>
 		  </div>
 		  <div>
 		    <%= f.label :spec %>
 		    <%= f.text_field :spec %>
 		  </div>
 		  <%= f.submit "送出" %>
 <% end %>

app/views/items/creat.html.erb
<h1 style="color: #3d7; font-family: 微軟正黑體;">CREAT</h1>

app/views/items/edit.html.erb
<h1>編輯餐點</h1>


<%= render 'form', item: @item %>

<!-- 寫在 _form/.html.erb -->

app/views/items/index.html.erb
<!-- <div class="container"> -->
	<h1 style="color: #d5a; font-family: 微軟正黑體;">餐點列表</h1>

	<%= link_to "新增", new_item_path %> 

<div class="row">
	<!-- <ul> -->
	<% @items.each do |item| %>
	<div class="col-4 mb-3">
			<!-- <li> -->
		<div class="card items">		
			<div class="cat">
					<%= image_tag item.cover.variant(resize_to_limit: [500, 500]), class:'cover-image' if item.cover.attached? %>	
			</div>
			<div class="card-body">
				<h5 class="card-title">
					<%= link_to item.name, item %>
				</h5>
					<%= link_to "編輯", edit_item_path(item.id), class:'btn btn-primary' %>		
  				<%= link_to "刪除", item_path(item.id), method: "delete", data: {confirm: "確定刪除?"}, class:'btn btn-success' %>
  				<%= link_to "加到購物車", add_to_cart_item_path(item), method: 'post', data: {confirm: "加到購物車"}, class:'btn btn-danger' %>
					<!-- </li> -->
		  </div>
		</div>
	</div>
	<% end %>
	<!-- </ul> -->
</div>




app/views/items/new.html.erb
<h1 style="color: #3d7; font-family: 微軟正黑體;">新增餐點</h1>

<%= render 'form', item: @item %>

<!-- 寫在 _form/.html.erb -->

app/views/items/show.html.erb
<h1 data-controller="item">
  <%= @item.name %>(<%= @item.price %> 元)
  <a href="#" class="btn btn-danger" data-action="item#heart">
    <% if @item.favorited_by(current_user) %>
      <i class="fas fa-heart" data-target="item.icon"></i>
    <% else %>
      <i class="far fa-heart" data-target="item.icon"></i>
    <% end %>
  </a>
 

</h1>


<div data-controller="comment">
  <h3>留言</h3>
  <%= form_for(@comment, url: item_comments_path(@item), remote: true) do |form| %>
    <input type="hidden" id="item_id" value="<%= @item.id %>">
    <div class="form-group">
      <%= form.text_area :content, 
                         class: 'form-control', 
                         data: {target: 'comment.content', 
                                action: 'keyup->comment#check' } %>
    </div>

    <%= form.submit class: 'btn btn-success', disabled: true, data: {target: 'comment.submit' } %>
  <% end %>
</div>

<hr>

<div id="comments">
<% @comments.each do |comment| %>
  <%= render 'comments/comment', comment: comment %>
<% end %>
</div>

app/views/items/show_my.html.erb
<h1 data-controller="item">
<%= @item.name %>
  <a href="#" class="btn btn-danger" data-action="item#heart">
  	<% if @item.favorited_by(current_user) %>
  	<i class="fas fa-heart" data-target="item.icon"></i>
  	<% else %>
	  <i class="far fa-heart" data-target="item.icon"></i>
	  
	  <% end %>
  </a>
  <%= #link_to "加到購物車", add_to_cart_item_path(@item),method: 'post', class: 'btn btn-danger' %>
</h1>

<ul>
	<li>
		價錢 : <%= @item.price %>
	</li>
</ul>

<div data-controller="comment">
	<h3>留言</h3>
		<%= form_for(@comment, url: item_comments_path(@item), remote: true) do |form| %> 
		<input type="hidden" id="item_id" value="<%= @item.id %>">
		<div class="form-group">
		<%= form.text_area :content, 
		                    class:'form-control', 
				    data: {target: 'comment.content', 
				    action: 'keyup->comment#check' } %>
		</div>
		<%= form.submit class: 'btn btn-success', disabled: true, data: {target:'comment.submit'} %>
	<% end %>
	<!-- url是在routes.rb做一條留言的連結，加 @item 才找得到 -->
</div>


<div id="comments">
<% @comments.each do |comment| %>
<%= render 'comments/comment', comment: comment %>
	
<% end %>
</div>
<!-- .order(id: :desc) 讓他正向排列-->
